apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpaas-antimalware
  labels:
    app: bpaas-antimalware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpaas-antimalware
  template:
    metadata:
      labels:
        app: bpaas-antimalware
    spec:
      containers:
        - image: ykel/node-antimalware #meylvpkshrbr01.mscloudinfra.com/consensys/bpaas-antimalware:f17bdc2 #
          name: bpaas-antimalware
          env:
            - name: CLAMAV_ENDPOINT
              value: "clamav.clamav-io"
            - name: CLAMAV_PORT
              value: "3310"
            - name: MESSAGE_BROKER_ENDPOINT
              value: "nats://nats.nats-io"
            - name: MESSAGE_BROKER_PORT
              value: "4222"
            - name: MINIO_ENDPOINT
              value: "minio.minio-io"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_BUCKET
              value: bpaas-files
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
