apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav # has to match .spec.template.metadata.labels
  strategy:
    # Specifies the strategy used to replace old Pods by new ones
    # Refer: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    type: Recreate
  template:
    metadata:
      labels:
        # This label is used as a selector in Service definition
        app: clamav
    spec:
      containers:
        - name: clamav
          # Pulls the lastest Minio image from Docker Hub
          image: mkodockx/docker-clamav:alpine
          ports:
            - containerPort: 3310

---
apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: clamav-service
spec:
  type: ClusterIP
  ports:
    - port: 3310
      targetPort: 3310
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: clamav
