apiVersion: v1
kind: Service
metadata:
  labels:
    name: nats
  name: nats
  namespace: nats-io
spec:
  ports:
    - name: connection
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: management
      port: 8222
      targetPort: 8222
  selector:
    app: nats
  type: ClusterIP
